---
# tasks file for modprobe
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: load requested modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ modprobe_modules }}"
  when:
    - modprobe_modules is defined
